allow_remote_control yes

copy_on_select yes
mouse_hide_wait 2
mouse_map cmd+alt+left press ungrabbed mouse_selection rectangle


# window
initial_window_width  160c
initial_window_height 50c
remember_window_size  no

map cmd+enter    toggle_fullscreen
macos_option_as_alt left


# font
disable_ligatures always
font_family      Maple Mono NF CN
font_size        13.0


# include secondary config files
include themes/macchiato.conf
