format = """
${custom.proxy}${custom.pyenv}$all
"""

[custom.proxy]
when = "test ! -z $http_proxy"
symbol = "📡 "
format = "$symbol"

[custom.pyenv]
when = "which pip"
symbol = "🔗 "
style = "bold orange"
format = "[$symbol]($style)"

[time]
disabled = false
time_format = '%Y-%m-%d %T'

[status]
disabled = false
symbol = '👺 '

[python]
pyenv_prefix = ''
pyenv_version_name = true

[jobs]
number_threshold = 1
