format = """
${custom.proxy}$all
"""

[custom.proxy]
when = "test ! -z $http_proxy"
symbol = "📡 "
format = "$symbol"

[time]
disabled = false
time_format = '%Y-%m-%d %T'

[status]
disabled = false
symbol = '👺 '

[python]
pyenv_prefix = ''
pyenv_version_name = true

[jobs]
number_threshold = 1
